Update Test.yml

diff --git a/.github/workflows/Test.yml b/.github/workflows/Test.yml
--- a/.github/workflows/Test.yml
+++ b/.github/workflows/Test.yml
@@ -10,45 +10,60 @@ jobs:
       matrix:
         os: [ubuntu-latest]
     steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - name: Run setup-java with the cache for maven
-        uses: itchyny/setup-java@feat-cache-dependency-path
-        id: setup-java
+      - uses: actions/checkout@v4
+      - name: Set up Maven Central Repository
+        uses: actions/setup-java@v3
         with:
-          distribution: 'adopt'
-          java-version: '11'
-          cache: maven
-          cache-dependency-path: "./*pom.xml"
-      - name: Create files to cache
-        run: |
-          mvn verify -f ./pom.xml
-          if [ ! -d ~/.m2/repository ]; then
-            echo "::error::The ~/.m2/repository directory does not exist unexpectedly"
-            exit 1
-          fi
-  maven-restore:
-    runs-on: ${{ matrix.os }}
-    strategy:
-      fail-fast: false
-      matrix:
-        os: [ubuntu-latest]
-    needs: maven-save
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - name: Run setup-java with the cache for maven
-        uses: itchyny/setup-java@feat-cache-dependency-path
-        id: setup-java
-        with:
-          distribution: 'adopt'
-          java-version: '11'
-          cache: maven
-          cache-dependency-path: "./pom.xml"
-      - name: Confirm that ~/.m2/repository directory has been made
-        run: |
-          if [ ! -d ~/.m2/repository ]; then
-            echo "::error::The ~/.m2/repository directory does not exist unexpectedly"
-            exit 1
-          fi
-          ls ~/.m2/repository
+          java-version: '8'
+          distribution: 'temurin'
+          cache: 'maven'
+          server-id: ossrh
+          server-username: OSSRH_USERNAME
+          server-password: OSSRH_PASSWORD
+          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
+          gpg-passphrase: GPG_PASSPHRASE
+      - run: |
+           gpg -version
+           cat $HOME/.m2/settings.xml
+      # - name: Checkout
+      #   uses: actions/checkout@v4
+      # - name: Run setup-java with the cache for maven
+      #   uses: itchyny/setup-java@feat-cache-dependency-path
+      #   id: setup-java
+      #   with:
+      #     distribution: 'adopt'
+      #     java-version: '11'
+      #     cache: maven
+      #     cache-dependency-path: "./*pom.xml"
+      # - name: Create files to cache
+      #   run: |
+      #     mvn verify -f ./pom.xml
+      #     if [ ! -d ~/.m2/repository ]; then
+      #       echo "::error::The ~/.m2/repository directory does not exist unexpectedly"
+      #       exit 1
+      #     fi
+  # maven-restore:
+  #   runs-on: ${{ matrix.os }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       os: [ubuntu-latest]
+  #   needs: maven-save
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #     - name: Run setup-java with the cache for maven
+  #       uses: itchyny/setup-java@feat-cache-dependency-path
+  #       id: setup-java
+  #       with:
+  #         distribution: 'adopt'
+  #         java-version: '11'
+  #         cache: maven
+  #         cache-dependency-path: "./pom.xml"
+  #     - name: Confirm that ~/.m2/repository directory has been made
+  #       run: |
+  #         if [ ! -d ~/.m2/repository ]; then
+  #           echo "::error::The ~/.m2/repository directory does not exist unexpectedly"
+  #           exit 1
+  #         fi
+  #         ls ~/.m2/repository
